// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crossconnect.proto

package crossconnect

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	networkservice "github.com/networkservicemesh/api/pkg/api/networkservice"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CrossConnectEventType int32

const (
	CrossConnectEventType_INITIAL_STATE_TRANSFER CrossConnectEventType = 0
	CrossConnectEventType_UPDATE                 CrossConnectEventType = 1
	CrossConnectEventType_DELETE                 CrossConnectEventType = 2
)

var CrossConnectEventType_name = map[int32]string{
	0: "INITIAL_STATE_TRANSFER",
	1: "UPDATE",
	2: "DELETE",
}

var CrossConnectEventType_value = map[string]int32{
	"INITIAL_STATE_TRANSFER": 0,
	"UPDATE":                 1,
	"DELETE":                 2,
}

func (x CrossConnectEventType) String() string {
	return proto.EnumName(CrossConnectEventType_name, int32(x))
}

func (CrossConnectEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97acf85fcaabb3f6, []int{0}
}

type Metrics struct {
	Metrics              map[string]string `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_97acf85fcaabb3f6, []int{0}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetMetrics() map[string]string {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CrossConnectEvent struct {
	Type                 CrossConnectEventType    `protobuf:"varint,1,opt,name=type,proto3,enum=crossconnect.CrossConnectEventType" json:"type,omitempty"`
	CrossConnects        map[string]*CrossConnect `protobuf:"bytes,2,rep,name=cross_connects,json=crossConnects,proto3" json:"cross_connects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metrics              map[string]*Metrics      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CrossConnectEvent) Reset()         { *m = CrossConnectEvent{} }
func (m *CrossConnectEvent) String() string { return proto.CompactTextString(m) }
func (*CrossConnectEvent) ProtoMessage()    {}
func (*CrossConnectEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_97acf85fcaabb3f6, []int{1}
}

func (m *CrossConnectEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossConnectEvent.Unmarshal(m, b)
}
func (m *CrossConnectEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossConnectEvent.Marshal(b, m, deterministic)
}
func (m *CrossConnectEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossConnectEvent.Merge(m, src)
}
func (m *CrossConnectEvent) XXX_Size() int {
	return xxx_messageInfo_CrossConnectEvent.Size(m)
}
func (m *CrossConnectEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossConnectEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CrossConnectEvent proto.InternalMessageInfo

func (m *CrossConnectEvent) GetType() CrossConnectEventType {
	if m != nil {
		return m.Type
	}
	return CrossConnectEventType_INITIAL_STATE_TRANSFER
}

func (m *CrossConnectEvent) GetCrossConnects() map[string]*CrossConnect {
	if m != nil {
		return m.CrossConnects
	}
	return nil
}

func (m *CrossConnectEvent) GetMetrics() map[string]*Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CrossConnect struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              string                     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Source               *networkservice.Connection `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *networkservice.Connection `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CrossConnect) Reset()         { *m = CrossConnect{} }
func (m *CrossConnect) String() string { return proto.CompactTextString(m) }
func (*CrossConnect) ProtoMessage()    {}
func (*CrossConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_97acf85fcaabb3f6, []int{2}
}

func (m *CrossConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossConnect.Unmarshal(m, b)
}
func (m *CrossConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossConnect.Marshal(b, m, deterministic)
}
func (m *CrossConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossConnect.Merge(m, src)
}
func (m *CrossConnect) XXX_Size() int {
	return xxx_messageInfo_CrossConnect.Size(m)
}
func (m *CrossConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CrossConnect proto.InternalMessageInfo

func (m *CrossConnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CrossConnect) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *CrossConnect) GetSource() *networkservice.Connection {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *CrossConnect) GetDestination() *networkservice.Connection {
	if m != nil {
		return m.Destination
	}
	return nil
}

func init() {
	proto.RegisterEnum("crossconnect.CrossConnectEventType", CrossConnectEventType_name, CrossConnectEventType_value)
	proto.RegisterType((*Metrics)(nil), "crossconnect.Metrics")
	proto.RegisterMapType((map[string]string)(nil), "crossconnect.Metrics.MetricsEntry")
	proto.RegisterType((*CrossConnectEvent)(nil), "crossconnect.CrossConnectEvent")
	proto.RegisterMapType((map[string]*CrossConnect)(nil), "crossconnect.CrossConnectEvent.CrossConnectsEntry")
	proto.RegisterMapType((map[string]*Metrics)(nil), "crossconnect.CrossConnectEvent.MetricsEntry")
	proto.RegisterType((*CrossConnect)(nil), "crossconnect.CrossConnect")
}

func init() { proto.RegisterFile("crossconnect.proto", fileDescriptor_97acf85fcaabb3f6) }

var fileDescriptor_97acf85fcaabb3f6 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5b, 0x6f, 0xd3, 0x30,
	0x18, 0x25, 0xe9, 0x58, 0xc5, 0xd7, 0x52, 0x05, 0xb3, 0x55, 0x51, 0x5e, 0x98, 0xca, 0xcb, 0xc4,
	0x25, 0x99, 0xc2, 0x03, 0xd3, 0x34, 0x21, 0x95, 0x2e, 0x93, 0x2a, 0xb6, 0x89, 0x65, 0xe1, 0x01,
	0x84, 0x54, 0xa5, 0x89, 0x49, 0xad, 0x36, 0x76, 0x64, 0xbb, 0x45, 0x79, 0xe6, 0x8f, 0x20, 0x7e,
	0x29, 0xca, 0xa5, 0xe0, 0x68, 0x81, 0xbe, 0x24, 0x9f, 0x8f, 0x8f, 0xcf, 0xf1, 0x77, 0x31, 0xa0,
	0x88, 0x33, 0x21, 0x22, 0x46, 0x29, 0x8e, 0xa4, 0x9d, 0x71, 0x26, 0x19, 0xea, 0xab, 0x98, 0x65,
	0xd4, 0x01, 0x61, 0xb4, 0xda, 0xb7, 0xcc, 0x4c, 0xe6, 0x19, 0x16, 0x0e, 0x4e, 0x33, 0x99, 0x57,
	0xdf, 0x6a, 0x67, 0xf4, 0x43, 0x83, 0xee, 0x35, 0x96, 0x9c, 0x44, 0x02, 0x9d, 0x43, 0x37, 0xad,
	0x42, 0x53, 0x3b, 0xea, 0x1c, 0xf7, 0xdc, 0x91, 0xdd, 0xf0, 0xaa, 0x79, 0xdb, 0xbf, 0x47, 0x25,
	0xcf, 0xfd, 0xed, 0x11, 0xeb, 0x0c, 0xfa, 0xea, 0x06, 0x32, 0xa0, 0xb3, 0xc4, 0xb9, 0xa9, 0x1d,
	0x69, 0xc7, 0x8f, 0xfc, 0x22, 0x44, 0x07, 0xf0, 0x70, 0x13, 0xae, 0xd6, 0xd8, 0xd4, 0x4b, 0xac,
	0x5a, 0x9c, 0xe9, 0xa7, 0xda, 0xe8, 0x67, 0x07, 0x9e, 0x4c, 0x0a, 0xab, 0x49, 0x65, 0xe5, 0x6d,
	0x30, 0x95, 0xe8, 0x2d, 0xec, 0x15, 0xd7, 0x2e, 0x25, 0x06, 0xee, 0xf3, 0xe6, 0x65, 0xee, 0xd1,
	0x83, 0x3c, 0xc3, 0x7e, 0x79, 0x00, 0x7d, 0x86, 0x41, 0xc9, 0x9d, 0xd5, 0x64, 0x61, 0xea, 0x65,
	0x3e, 0xee, 0x0e, 0x89, 0x06, 0x52, 0xe7, 0xf7, 0x38, 0x52, 0x31, 0x74, 0xf9, 0xb7, 0x46, 0x9d,
	0x52, 0xf3, 0xd5, 0x2e, 0xcd, 0xf6, 0x6a, 0x7d, 0x05, 0x74, 0xdf, 0xac, 0xa5, 0x66, 0x27, 0x6a,
	0xcd, 0x7a, 0xae, 0xf5, 0x6f, 0x37, 0xa5, 0x9e, 0xd6, 0xed, 0xce, 0x5e, 0xbc, 0x6c, 0xea, 0x1e,
	0xb6, 0x76, 0x5a, 0x6d, 0xd1, 0x2f, 0x0d, 0xfa, 0xaa, 0x1d, 0x1a, 0x80, 0x4e, 0xe2, 0x5a, 0x52,
	0x27, 0x31, 0x32, 0xa1, 0x9b, 0x85, 0xf9, 0x8a, 0x85, 0x71, 0xdd, 0xdf, 0xed, 0x12, 0xd9, 0xb0,
	0x2f, 0xd8, 0x9a, 0x47, 0xd8, 0xdc, 0x2b, 0xcd, 0x86, 0xb6, 0x32, 0xa0, 0x93, 0x3f, 0xa1, 0x5f,
	0xb3, 0xd0, 0x29, 0xf4, 0x62, 0x2c, 0x24, 0xa1, 0x61, 0x01, 0x9b, 0xdd, 0xff, 0x1e, 0x52, 0xa9,
	0x2f, 0x3e, 0xc0, 0x61, 0xeb, 0x5c, 0x20, 0x0b, 0x86, 0xd3, 0x9b, 0x69, 0x30, 0x1d, 0x5f, 0xcd,
	0xee, 0x82, 0x71, 0xe0, 0xcd, 0x02, 0x7f, 0x7c, 0x73, 0x77, 0xe9, 0xf9, 0xc6, 0x03, 0x04, 0xb0,
	0xff, 0xe9, 0xe3, 0xc5, 0x38, 0xf0, 0x0c, 0xad, 0x88, 0x2f, 0xbc, 0x2b, 0x2f, 0xf0, 0x0c, 0xdd,
	0x5d, 0xc0, 0xd3, 0x6b, 0x46, 0x89, 0x64, 0xbc, 0x91, 0xf7, 0x2d, 0x1c, 0xb4, 0xc0, 0x02, 0x0d,
	0xed, 0x84, 0xb1, 0x64, 0x85, 0xab, 0x87, 0x35, 0x5f, 0x7f, 0xb3, 0xbd, 0xe2, 0x9d, 0x59, 0xcf,
	0x76, 0x0c, 0xc8, 0x89, 0xf6, 0xfe, 0xdd, 0x97, 0xf3, 0x84, 0xc8, 0xc5, 0x7a, 0x6e, 0x47, 0x2c,
	0x75, 0x28, 0x96, 0xdf, 0x19, 0x5f, 0x0a, 0xcc, 0x37, 0x24, 0xc2, 0x29, 0x16, 0x0b, 0x27, 0x4a,
	0xe3, 0xd7, 0x54, 0xa4, 0x09, 0x77, 0xb2, 0x65, 0xe2, 0x84, 0x19, 0x71, 0x54, 0xcd, 0xf9, 0x7e,
	0x69, 0xf9, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x8d, 0xee, 0x3c, 0x1b, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MonitorCrossConnectClient is the client API for MonitorCrossConnect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorCrossConnectClient interface {
	MonitorCrossConnects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorCrossConnect_MonitorCrossConnectsClient, error)
}

type monitorCrossConnectClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorCrossConnectClient(cc grpc.ClientConnInterface) MonitorCrossConnectClient {
	return &monitorCrossConnectClient{cc}
}

func (c *monitorCrossConnectClient) MonitorCrossConnects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorCrossConnect_MonitorCrossConnectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MonitorCrossConnect_serviceDesc.Streams[0], "/crossconnect.MonitorCrossConnect/MonitorCrossConnects", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorCrossConnectMonitorCrossConnectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MonitorCrossConnect_MonitorCrossConnectsClient interface {
	Recv() (*CrossConnectEvent, error)
	grpc.ClientStream
}

type monitorCrossConnectMonitorCrossConnectsClient struct {
	grpc.ClientStream
}

func (x *monitorCrossConnectMonitorCrossConnectsClient) Recv() (*CrossConnectEvent, error) {
	m := new(CrossConnectEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorCrossConnectServer is the server API for MonitorCrossConnect service.
type MonitorCrossConnectServer interface {
	MonitorCrossConnects(*empty.Empty, MonitorCrossConnect_MonitorCrossConnectsServer) error
}

// UnimplementedMonitorCrossConnectServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorCrossConnectServer struct {
}

func (*UnimplementedMonitorCrossConnectServer) MonitorCrossConnects(req *empty.Empty, srv MonitorCrossConnect_MonitorCrossConnectsServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorCrossConnects not implemented")
}

func RegisterMonitorCrossConnectServer(s *grpc.Server, srv MonitorCrossConnectServer) {
	s.RegisterService(&_MonitorCrossConnect_serviceDesc, srv)
}

func _MonitorCrossConnect_MonitorCrossConnects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorCrossConnectServer).MonitorCrossConnects(m, &monitorCrossConnectMonitorCrossConnectsServer{stream})
}

type MonitorCrossConnect_MonitorCrossConnectsServer interface {
	Send(*CrossConnectEvent) error
	grpc.ServerStream
}

type monitorCrossConnectMonitorCrossConnectsServer struct {
	grpc.ServerStream
}

func (x *monitorCrossConnectMonitorCrossConnectsServer) Send(m *CrossConnectEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _MonitorCrossConnect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crossconnect.MonitorCrossConnect",
	HandlerType: (*MonitorCrossConnectServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorCrossConnects",
			Handler:       _MonitorCrossConnect_MonitorCrossConnects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crossconnect.proto",
}
